[package]
name = "crust-cage-compiler"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true

[dependencies]
prettyplease.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
